version: "3"
services:
  offload:
    build: .
    # image: figassis/wpoffload:0.0.1
    restart: always
    container_name: offload
    environment:
      LOGLEVEL: debug
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      BUCKET: ${BUCKET}
      PREFIX: ${PREFIX}
      WATCH: /data
      SCHEDULE: "* * * * *"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      ACCESS: "private"
    links:
      - cache
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
  cache:
    image: "redis:alpine"
    container_name: cache
    restart: always
    expose:
      - 6379
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "3"
